package id.holigo.services.common.model;

public enum StatusOrderEnum {
    PROCESS_BOOK, BOOKED, BOOK_FAILED, PROCESS_ISSUED, WAITING_ISSEUD, ISSUED, RETRYING_ISSUED, ISSUED_FAILED,
    ORDER_EXPIRED, ORDER_CANCELED
}
