package id.holigo.services.common.model;

public enum StatusPaymentEnum {
    WAITING_PAYMENT, VERIFYING_PAYMENT, PAYMENT_FAILED, PAID, PAYMENT_CANCELED, PAYMENT_EXPIRED, PROCESS_REFUND,
    WAITING_REFUND, REFUNDED
}
